---
title: "Artificial Intelligence Applied to Games"
author: 
    - "Contributors: Carlos Grilo, Catarina Silva, Pedro Gago"
subtitle: "Gustavo Reis, Luís Monteiro"
format: 
  revealjs:
    theme: dark
    transition: slide
    incremental: true
    slide-number: c/t
    show-slide-number: all
    footer: AIAG - Introduction to AI - Games and Multimedia
---

## Object and Goals

-   **Object**: Intelligent entities
-   **Goals**:
    -   Understand how they operate
    -   To build intelligent entities

## Approaches to AI

|   | **Human** | **Rational** |
|------|--------------------------------|-----------------------------|
| **Think** | "The exciting new effort to make computers think…" (Haugeland 1985) | "The study of computations that make it possible to perceive, reason and act" (Winston 1992) |
| **Act** | "The study of how to make computers do things at which at the moment people are better" (Rich & Knight 1992) | "The study and construction of rational agents" (Russell & Norvig 1995) |

::: notes
-   Four different quotes that sum the evolution of AI
-   Also represent four distinct jumps in the history of AI
    -   started with studying how humans think and act
    -   later how to create rational thinking and acting
:::

## Human Behaviour VS Rational Behaviour

“By distinguishing between [**human**]{.underline} and [**rational behavior**]{.underline} , we are [not suggesting that humans are necessarily “irrational”]{.underline} in the sense of “emotionally unstable” or “insane”. [**One merely needs to note that we are not perfect**]{.underline}: not all chess players are grandmasters, and, unfortunately, not everyone gets an A on the exam.”

## Approaches to AI

|   | [**Human**]{.underline} | **Rational** |
|------|-------------------------------|-----------------------------|
| [**Think**]{.underline} | ["The exciting new effort to make computers think…" (Haugeland 1985)]{.underline} | "The study of computations that make it possible to perceive, reason and act" (Winston 1992) |
| **Act** | "The study of how to make computers do things at which at the moment people are better" (Rich & Knight 1992) | "The study and construction of rational agents" (Russell & Norvig 1995) |

## Thinking Humanly

-   **Goal**: Simulation of the human way of reasoning
-   **Requirements**:
    -   Scientific theories about human brain activity (cognitive science & cognitive neuroscience)
    -   One needs to define the abstraction level at which human reasoning should be modeled (knowledge ↔ circuits)
-   **Historical example**: General Problem Solver (1961)

::: notes
-   Objective: Simulate or reproduce the way humans reason

-   Needs studies in cognitive science and cognitive neuroscience. cognitive neuroscience is a subfield of cognitive science.

-   General problem solver: A computer program created to work as an universal problem solving machine.
:::

## Approaches to AI

|   | [**Human**]{.underline} | **Rational** |
|-------|-------------------------------|-----------------------------|
| **Think** | "The exciting new effort to make computers think…" (Haugeland 1985) | "The study of computations that make it possible to perceive, reason and act" (Winston 1992) |
| [**Act**]{.underline} | ["The study of how to make computers do things at which at the moment people are better" (Rich & Knight 1992)]{.underline} | "The study and construction of rational agents" (Russell & Norvig 1995) |

## Acting Humanly

-   **Goal**: Simulation of the human behavior
-   **Problem**: How can we verify if the goal has been accomplished?
-   **Answer**: Turing Test

::: notes
-   Turing Test: sitting next to a machine, it you detect it is a machine, it fails the test
:::

## Acting Humanly

-   **Turing Test**: Turing suggested that a machine should have the following capabilities in order to pass the test
    -   Automated reasoning
    -   Knowledge representation
    -   Machine learning
    -   Natural language processing

::: notes
-   Automated reasoning - raciocinar
-   Knowledge representation - possuir conhecimento sobre o mundo que possa utilizar para resolver problemas
-   Machine Learning - sistemas devem aprender com dados, identificar padroes e tomar decisoes com o minimo de intervençao humana
-   Natural language processing - maneira da máquina comunicar através da linguagem, perceber, gerar e reconhecer
:::

## Acting Humanly

-   **Turing Test**:
    -   In order to pass the test, a machine should interact with a person so that the latter doesn’t notice that she/he is interacting with a machine

    -   <div>

        > Turing predicted that by 2000, a machine would have a 30% chance of deceiving a person for 5 minutes

        </div>

    -   *How did this prediction turn out?*

## Approaches to AI

|   | **Human** | [**Rational**]{.underline} |
|------|-------------------------------|-----------------------------|
| [**Think**]{.underline} | "The exciting new effort to make computers think…" (Haugeland 1985) | ["The study of computations that make it possible to perceive, reason and act" (Winston 1992)]{.underline} |
| **Act** | "The study of how to make computers do things at which at the moment people are better" (Rich & Knight 1992) | "The study and construction of rational agents" (Russell & Norvig 1995) |

## Thinking Rationally

-   **Goal**: to build agents that generate irrefutable reasoning (logic reasoning)
-   **Problems with pure logic**:
    -   Difficult to represent informal knowledge formally
        -   **Example**: it's difficult to represent uncertainty
    -   Can be impractical for real problems
    -   Not all intelligent behavior is logical

::: notes
-   It can render impractical to solve real problems Tudo muito bonito na Teoria, mas na pratica quando se mete as mãos na massa…

-   Not all intelligent behavior is logical Sometimes our actions are not based on logical decisions, for example emotional reactions
:::

## Approaches to AI

|   | **Human** | [**Rational**]{.underline} |
|------|-------------------------------|-----------------------------|
| **Think** | "The exciting new effort to make computers think…" (Haugeland 1985) | "The study of computations that make it possible to perceive, reason and act" (Winston 1992) |
| [**Act**]{.underline} | "The study of how to make computers do things at which at the moment people are better" (Rich & Knight 1992) | ["The study and construction of rational agents" (Russell & Norvig 1995)]{.underline} |

## Acting Rationally

-   **Goal**: to build agents that perform tasks in a rational way
-   **Rational Agent**: Acts to achieve best possible outcome (or best [expected]{.underline} outcome under uncertainty)
-   **Key differences between acting and thinking rationally**:
    -   Sometimes there is no "right" thing to do, but action is still needed
    -   Sometimes there is no time to think - only react (example: reacting to contact with a very hot surface)

::: notes
-   Objetivo é construir agentes que realizem tarefas de forma puramente racional
-   Um agente racional, vai agir de forma a alcançar o melhor resultado possivel, OU, se houver incerteza, o melhor resultado ESPERADO
-   Morally gray choices – Lives of a few versus lives of many
:::

## AI Foundations: Philosophy

-   Socrates, Plato, Aristotle
-   First algorithm (Socrates)
-   Dualism (Descartes) part of the mind is not subject to the laws of physics
-   Materialism: the human brain acts according to the laws of physics
-   Theories about knowledge: Empiricism
-   Link between observation and knowledge

::: notes
-   Descartes Dualism - exploring the separation of mind and body
-   Materialism – the meaning we attribute to matter (matéria fisica)
-   Empiricism: theory defends that knowledge is acquired only through our senses (sight, hearing, etc.).
:::

## AI Foundations: Mathematics

-   Mathematical algorithms (al Khwārizmī, 9th century)
-   Logic, logic inference
-   Studies about the impossibility of asserting the truth of some statements
-   Turing machine (capable of executing any “computable” function)
-   Impossibility of dealing with certain problems (dimension)
-   Probability theory • Decision theory

## AI Foundations: Psychology

-   **Introspection**: Studying reasoning processes
-   **Behaviorism**: only observable behavior should be studied (good results with animals…)
-   **Cognitive Psychology**: View the brain as an information processing device

## AI History: Birth (1943-1956)

-   **1943**: W. Macculloch & W. Pitts - proposed a model of artificial - artificial neuron model
-   **1950s**: C. Shannon & A. Turing - were already writing programs to play chess (even without access to computers…)
-   **1950s**: A. Newell & H. Simon - developed a program capable of proving mathematical theorems
-   **1956**: Workshop where the term "Artificial Intelligence" was born

## AI History: Early Enthusiasm, great expectations (1952-1969)

-   In this period, many problems were solved whose resolution by computers was considered to be impossible
-   A. Samuel developed a program that learned to play checkers at strong amateur level (being able to beat him also)
-   The Lisp programming language was created in this period
-   A. Newell and H. Simon developed the **General Problem Solver**, with the goal of simulating human reasoning in the resolution of simple problems

## AI History: Early Enthusiasm, great expectations (1952-1969)

-   Time Sharing (DEC)
-   Microworlds (problems solved in a controlled environment)
    -   Most notable example: Blocks world

::: notes
Time Sharing: Before time-sharing, computers operated in "batch mode" - you would submit your program on punch cards, wait hours or days for results, then get a printout back. How CPUs evolved to interactive / live development.

Blocks world: era uma especie de programa que faz lembrar um jogo, em que se resolvia problemas movendo os cubos (por exemplo ordenar os cubos movendo apenas 1 de cada vez)
:::

## AI History: Reality Check (1966-1974)

-   In 1958, H. Simon predicted that within 10 years, a computer would be chess champion and a significant mathematical theorem would be proved by a computer!!!

-   However…

    -   Programs knew nothing about their subject matter; They succeeded by simple syntactic manipulation
        -   Example: by simple syntactic manipulation, the sentence “The spirit is willing but the flesh is weak” was translated as “The vodka is good but the meat is rotten”…
    -   The methods able to solve simple problems were not able to solve general and difficult problems

## AI History: Reality Check (1966-1974)

-   Computers had not enough computational power to solve “larger” problems
-   Difficulties due to computational limitations - genetic algorithms (“good” idea, but impossible to verify with existent hardware)
-   “Perceptrons” book (Minsky and Papert, 1969) that, among other things, address perceptron limitations
-   Strong decrease in AI research funding (the so called “AI Winter”)
-   [(Only) in 1997 a computer was able to beat the human chess world champion]{.underline}

## AI History: Knowledge-Based Systems (1969-1979)

-   Realized the necessity of using knowledge about the problem to solve, in order to achieve better results
-   **Expert systems**: systems intended to simulate the reasoning of an expert in a given area
    -   Examples: Tendril (molecular structures identification), MyCin (bacteria identification)
-   Expert systems led to a strong effort in the development of knowledge representation methods
-   Creation of the **Prolog** programming language

## AI History: Summarized (1980-Present)

-   **1980+**: AI becomes profitable

    -   AI starts to pay: expert systems, robotics, vision systems

-   **1986+**: Neural networks return

    -   Mainly due to the Back propagation algorithm

-   **1987+**: AI adopts the scientific method

-   [It is now more common to build on existing theories than to propose brand new ones , to base claims on rigorous theorems or her experimental evidence rather than on intuition , and to show relevance to real world applications rather than toy examples]{.underline}

## Modern AI Applications

::::: columns
::: {.column width="50%"}
-   Systems control
-   Automated driving
-   Speech recognition
-   Image recognition
-   Translation systems
:::

::: {.column width="50%"}
-   Failure detection
-   Disease diagnostics
-   Robotics
-   Games
-   And many more...
:::
:::::

## Philosophical Questions

1.  **Intelligence measurement**: Is a program with 200 IQ more intelligent than humans?

2.  **Computational limits**: Are there unsolvable problems that make AI impossible?

3.  **Resource constraints**: Some problems require too many computational resources

::: notes
200 IQ – Points to consider, - IQ is a limited measure (designed to measure specific type of inteligence, primarly logical and mathematical reasoning) - AI excels in tasks that require processing vasts ammount of data and complex calculations. Lacks in human intution, empathy, understanding contexts.
:::

------------------------------------------------------------------------